version: '3.4'

services:
  aqualux.services.identity.api:
    image: kamil1225/aqualux-identity:v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__AquaDb=Server=tcp:sampleapitestdb.database.windows.net,1433;Initial Catalog=aqua-db;Persist Security Info=False;User ID=sampleadmin;Password=password123!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    ports:
      - "443"
      - "80"
    container_name: aqualux.services.identity  
  
  aqualux.services.customers.api:
    image: kamil1225/aqualux-customers:v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__AquaDb=Server=tcp:sampleapitestdb.database.windows.net,1433;Initial Catalog=aqua-db;Persist Security Info=False;User ID=sampleadmin;Password=password123!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    ports:
      - "80"
      - "443"
    container_name: aqualux.services.customers.api

  aqualux.gateway:
    image: kamil1225/aqualux-gateway:v1
    build:
      context: .
      dockerfile: aqualux.gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 5000:80
    container_name: aqualux.gateway

